# SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[toolchain]
channel = "nightly-2023-08-20"
components = ["rustfmt", "clippy", "rustc"]
targets = []
profile = "minimal"
