# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[env]
DYLD_LIBRARY_PATH = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/'
CROSS_COMPILE = "arm-none-eabi"

[build]
target = "armv7a-none-eabi"
